name: MyClip
options:
  bundleIdPrefix: cc.vibevibe
  deploymentTarget:
    macOS: "26.0"
  xcodeVersion: "26.0"
settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "26.0"
    GENERATE_INFOPLIST_FILE: NO
schemes:
  MyClip:
    build:
      targets:
        MyClip: all
packages:
  MyClipCore:
    path: .
  WChatClawSwift:
    url: https://github.com/section9-lab/wchat-claw-swfit.git
    branch: main
  Textual:
    url: https://github.com/gonzalezreal/textual.git
    exactVersion: 0.5.0
targets:
  MyClip:
    type: application
    platform: macOS
    deploymentTarget: "26.0"
    sources:
      - path: MyClip
        excludes:
          - Core/**
          - Supporting/AppIcon.icon/**
          - Supporting/IconSources/**
          - Supporting/Kara.icns
    dependencies:
      - package: MyClipCore
        product: MyClipCore
      - package: WChatClawSwift
        product: WChatClawSwift
      - package: Textual
        product: Textual
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: cc.vibevibe.myclip
        PRODUCT_NAME: MyClip
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: E04719740CD0DF70E4D0CA1B42ABBD273B4E0F9A
        DEVELOPMENT_TEAM: YP86S77K2X
        INFOPLIST_FILE: MyClip/Supporting/Info.plist
        CODE_SIGN_ENTITLEMENTS: MyClip/Supporting/MyClip.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        LSUIElement: YES
