"""Capture actual MCP replies against the same fictional notes displayed by the HTML demo."""
import hashlib
import json
import pathlib
import subprocess
import tempfile

repo = pathlib.Path(__file__).resolve().parents[3]
binary = repo / '.build/debug/myclip-mcp'
if not binary.exists():
    subprocess.run(['swift', 'build', '--product', 'myclip-mcp'], cwd=repo, check=True)
# Read the shared JavaScript fixture in an isolated Node context; no browser or app is launched.
fixture = pathlib.Path(__file__).parent.parent / 'app-data.js'
reader = """import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
const context = {window: {}};
runInNewContext(readFileSync(process.argv[1], 'utf8'), context);
console.log(JSON.stringify(context.window.MYCLIP_APP_DATA.documents));"""
documents = json.loads(subprocess.run(['node', '--input-type=module', '-e', reader, str(fixture)], text=True, capture_output=True, check=True).stdout)
notes = {document['path']: document['markdown'] for document in documents}
assert {'Memory.md', 'Now.md'} <= notes.keys()
requests = [
    {'jsonrpc': '2.0', 'id': 1, 'method': 'initialize', 'params': {'protocolVersion': '2025-11-25', 'capabilities': {}, 'clientInfo': {'name': 'myclip-html-demo', 'version': '1'}}},
    {'jsonrpc': '2.0', 'id': 2, 'method': 'tools/call', 'params': {'name': 'memory_search', 'arguments': {'query': '演示', 'limit': 5}}},
    {'jsonrpc': '2.0', 'id': 3, 'method': 'tools/call', 'params': {'name': 'memory_get', 'arguments': {'path': 'Memory.md#最近的决定'}}},
    {'jsonrpc': '2.0', 'id': 4, 'method': 'tools/call', 'params': {'name': 'memory_get', 'arguments': {'path': 'Now.md'}}},
]
with tempfile.TemporaryDirectory(prefix='MyClip-Recall-Demo-') as folder:
    root = pathlib.Path(folder)
    for path, body in notes.items():
        file = root / 'Memory' / path
        file.parent.mkdir(parents=True, exist_ok=True)
        file.write_text(body)
    result = subprocess.run([str(binary), '--library', folder], input=''.join(json.dumps(q, ensure_ascii=False) + '\n' for q in requests), text=True, capture_output=True, check=True)
    replies = [json.loads(line) for line in result.stdout.splitlines()]
assert len(replies) == 4
assert all('error' not in reply and not reply.get('result', {}).get('isError') for reply in replies)
output = {'fixture': 'app-data.js fictional notes', 'executable_sha256': hashlib.sha256(binary.read_bytes()).hexdigest(), 'requests': requests[1:], 'replies': replies[1:]}
path = pathlib.Path(__file__).parent.parent / 'assets/recall.json'
path.write_text(json.dumps(output, ensure_ascii=False, indent=2) + '\n')
path.with_name('recall-data.js').write_text('/* Generated by scripts/recall.py; do not edit. */\nwindow.MYCLIP_RECALL = ' + json.dumps(output, ensure_ascii=False, indent=2) + ';\n')
print(path)
print('Verified memory_search + 2 memory_get calls against an isolated library.')
